# Generated by Django 5.2 on 2025-04-17 12:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('platform', models.CharField(choices=[('reddit', 'Reddit'), ('4chan', '4chan')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('post_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('cryptocurrency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypto_sentiment.cryptocurrency')),
            ],
        ),
        migrations.CreateModel(
            name='SentimentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment_type', models.CharField(choices=[('popularity', 'Popularité'), ('utility', 'Utilité'), ('investment', "Potentiel d'investissement"), ('stability', 'Stabilité'), ('innovation', 'Innovation')], max_length=20)),
                ('score', models.FloatField(default=50.0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment_analyses', to='crypto_sentiment.socialmediapost')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('post', 'sentiment_type')},
            },
        ),
    ]
